# Generated by Django 4.2.3 on 2023-07-17 21:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('transaction_title', models.CharField(max_length=150)),
                ('transaction_amount', models.FloatField()),
                ('transaction_currency', models.CharField(choices=[('$', '$'), ('C$', 'C$')], max_length=10)),
                ('transaction_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=10)),
                ('transaction_creation_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_description', models.TextField(null=True)),
                ('transaction_keywords', models.TextField()),
            ],
        ),
    ]
